# This file was generated by GoReleaser. DO NOT EDIT.
cask "kb" do
  name "kb"
  desc "A CLI knowledge base backed by SQLite — store, search, and link markdown documents with YAML frontmatter metadata"
  homepage "https://github.com/misham/kb"
  version "1.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/misham/kb/releases/download/v#{version}/kb-darwin-amd64"
      sha256 "9e996b8167755a7b3a32cdffa4ac95796546e001b07b1aba1327a6a63471c083"
      binary "kb-darwin-amd64", target: "kb"
    end
    on_arm do
      url "https://github.com/misham/kb/releases/download/v#{version}/kb-darwin-arm64"
      sha256 "088a9dd436f7f581dce9eedcf09f9dbd085f33ad9e8d16aedd44fc4448bcf666"
      binary "kb-darwin-arm64", target: "kb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/misham/kb/releases/download/v#{version}/kb-linux-amd64"
      sha256 "64fd9bacd4be0d8d4d961c805c9a3d43466c36fba0201a5b4bce62968168ac30"
      binary "kb-linux-amd64", target: "kb"
    end
  end

  # No zap stanza required
end
