# This file was generated by GoReleaser. DO NOT EDIT.
cask "lnr" do
  name "lnr"
  desc "A CLI for Linear project management — manage issues, projects, cycles, and initiatives from the terminal"
  homepage "https://github.com/misham/linear-cli"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/misham/lnr/releases/download/v#{version}/lnr-darwin-amd64"
      sha256 "37e9df9b140f9f62b5cc8047c6ec78c6df0f73efd31ea55c7e7f25f2a2d32805"
      binary "lnr-darwin-amd64", target: "lnr"
    end
    on_arm do
      url "https://github.com/misham/lnr/releases/download/v#{version}/lnr-darwin-arm64"
      sha256 "d87700ccb95e4bce50b8b33821f3abedb1969f1edcab270437519023cd88aeff"
      binary "lnr-darwin-arm64", target: "lnr"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/misham/lnr/releases/download/v#{version}/lnr-linux-amd64"
      sha256 "6202424a0f6e78cf97e3a82d26fa0a7e747f6f209a355e29a730a9c8ba3275c1"
      binary "lnr-linux-amd64", target: "lnr"
    end
  end

  postflight do
    system_command "/bin/sh", args: ["-c", "/usr/bin/xattr -dr com.apple.quarantine #{staged_path}/lnr-*"]
  end

  # No zap stanza required
end
